params.lo: /Users/kentchen/GitHub/php/php-5.5.20/ext/params/params.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/kentchen/GitHub/php/php-5.5.20/ext/params $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/kentchen/GitHub/php/php-5.5.20/ext/params/params.c -o params.lo 
$(phplibdir)/params.la: ./params.la
	$(LIBTOOL) --mode=install cp ./params.la $(phplibdir)

./params.la: $(shared_objects_params) $(PARAMS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_params) $(PARAMS_SHARED_LIBADD)

