consts.lo: /Users/kentchen/GitHub/php/php-5.5.20/ext/consts/consts.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/kentchen/GitHub/php/php-5.5.20/ext/consts $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/kentchen/GitHub/php/php-5.5.20/ext/consts/consts.c -o consts.lo 
$(phplibdir)/consts.la: ./consts.la
	$(LIBTOOL) --mode=install cp ./consts.la $(phplibdir)

./consts.la: $(shared_objects_consts) $(CONSTS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_consts) $(CONSTS_SHARED_LIBADD)

