return.lo: /Users/kentchen/GitHub/php/php-5.5.20/ext/return/return.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/kentchen/GitHub/php/php-5.5.20/ext/return $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/kentchen/GitHub/php/php-5.5.20/ext/return/return.c -o return.lo 
$(phplibdir)/return.la: ./return.la
	$(LIBTOOL) --mode=install cp ./return.la $(phplibdir)

./return.la: $(shared_objects_return) $(RETURN_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_return) $(RETURN_SHARED_LIBADD)

