resource.lo: /Users/kentchen/GitHub/php/php-5.5.20/ext/resource/resource.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/kentchen/GitHub/php/php-5.5.20/ext/resource $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/kentchen/GitHub/php/php-5.5.20/ext/resource/resource.c -o resource.lo 
$(phplibdir)/resource.la: ./resource.la
	$(LIBTOOL) --mode=install cp ./resource.la $(phplibdir)

./resource.la: $(shared_objects_resource) $(RESOURCE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_resource) $(RESOURCE_SHARED_LIBADD)

