objects1.lo: /Users/kentchen/GitHub/php/php-5.5.20/ext/objects1/objects1.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/kentchen/GitHub/php/php-5.5.20/ext/objects1 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/kentchen/GitHub/php/php-5.5.20/ext/objects1/objects1.c -o objects1.lo 
$(phplibdir)/objects1.la: ./objects1.la
	$(LIBTOOL) --mode=install cp ./objects1.la $(phplibdir)

./objects1.la: $(shared_objects_objects1) $(OBJECTS1_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_objects1) $(OBJECTS1_SHARED_LIBADD)

