array.lo: /Users/kentchen/GitHub/php/php-5.5.20/ext/array/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/kentchen/GitHub/php/php-5.5.20/ext/array $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/kentchen/GitHub/php/php-5.5.20/ext/array/array.c -o array.lo 
$(phplibdir)/array.la: ./array.la
	$(LIBTOOL) --mode=install cp ./array.la $(phplibdir)

./array.la: $(shared_objects_array) $(ARRAY_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_array) $(ARRAY_SHARED_LIBADD)

