fcall.lo: /Users/kentchen/GitHub/php/php-5.5.20/ext/fcall/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/kentchen/GitHub/php/php-5.5.20/ext/fcall $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/kentchen/GitHub/php/php-5.5.20/ext/fcall/fcall.c -o fcall.lo 
$(phplibdir)/fcall.la: ./fcall.la
	$(LIBTOOL) --mode=install cp ./fcall.la $(phplibdir)

./fcall.la: $(shared_objects_fcall) $(FCALL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_fcall) $(FCALL_SHARED_LIBADD)

